#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_VICTORY)             += input-core.o
input-core-objs := input.o input-compat.o ff-core.o
~                                                                                                                                                                      
~                                                                                                                                                                      
~                    
