#
# Makefile for the s3c-kepad melfas-touchkey drivers for Atlas.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KEYPAD_S3C_VICTORY)     += s3c-keypad.o
obj-$(CONFIG_KEYPAD_MELFAS_TOUCH_VICTORY)                += melfas-touchkey.o
obj-$(CONFIG_KEYPAD_MELFAS_TOUCH_VICTORY)                += melfas_download.o

